// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT5rS1MHkJz07y3RllXOQKjrOk4FgRRps',
    appId: '1:30218697114:web:4235c21d376ad6c4c66223',
    messagingSenderId: '30218697114',
    projectId: 'dalel-app-e2b02',
    authDomain: 'dalel-app-e2b02.firebaseapp.com',
    storageBucket: 'dalel-app-e2b02.firebasestorage.app',
    measurementId: 'G-1ESFZL9GXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9QwW-MdyJnVWmbT4a-ia9eKh2I3sFvnk',
    appId: '1:30218697114:android:bd8987a42b247da7c66223',
    messagingSenderId: '30218697114',
    projectId: 'dalel-app-e2b02',
    storageBucket: 'dalel-app-e2b02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXBLvJKj5y044i2hOymO3O5JYYx3LZTWk',
    appId: '1:30218697114:ios:6da13e42661cd05ac66223',
    messagingSenderId: '30218697114',
    projectId: 'dalel-app-e2b02',
    storageBucket: 'dalel-app-e2b02.firebasestorage.app',
    iosBundleId: 'com.example.dalelProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXBLvJKj5y044i2hOymO3O5JYYx3LZTWk',
    appId: '1:30218697114:ios:6da13e42661cd05ac66223',
    messagingSenderId: '30218697114',
    projectId: 'dalel-app-e2b02',
    storageBucket: 'dalel-app-e2b02.firebasestorage.app',
    iosBundleId: 'com.example.dalelProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT5rS1MHkJz07y3RllXOQKjrOk4FgRRps',
    appId: '1:30218697114:web:c14b1d6a03eed6f7c66223',
    messagingSenderId: '30218697114',
    projectId: 'dalel-app-e2b02',
    authDomain: 'dalel-app-e2b02.firebaseapp.com',
    storageBucket: 'dalel-app-e2b02.firebasestorage.app',
    measurementId: 'G-WGH79HB3FV',
  );
}
